// Archivo de 366 frases atemporales para el alma, enfocado en la calma, el presente y la sabiduría.

const finalQuotes = [
    { text: "La felicidad de tu vida depende de la calidad de tus pensamientos.", author: "Marco Aurelio" },
    { text: "El viaje de mil millas comienza con un solo paso.", author: "Lao-Tsé" },
    { text: "No es que tengamos poco tiempo, sino que perdemos mucho.", author: "Séneca" },
    { text: "El arte de vivir es más parecido a la lucha que a la danza.", author: "Marco Aurelio" },
    { text: "La mejor venganza es ser diferente a quien causó el daño.", author: "Marco Aurelio" },
    { text: "Concéntrate en el momento presente. Es la única realidad que tienes.", author: "Eckhart Tolle" },
    { text: "La simplicidad es la máxima sofisticación.", author: "Leonardo da Vinci" },
    { text: "Si estás deprimido, vives en el pasado. Si estás ansioso, vives en el futuro. Si estás en paz, vives en el presente.", author: "Lao-Tsé" },
    { text: "No te expliques. Tus amigos no lo necesitan y tus enemigos no te creerán.", author: "Marco Aurelio" },
    { text: "La riqueza no consiste en tener grandes posesiones, sino en tener pocas necesidades.", author: "Epicteto" },
    { text: "La vida es muy simple, pero insistimos en hacerla complicada.", author: "Confucio" },
    { text: "El obstáculo es el camino.", author: "Proverbio Zen" },
    { text: "Todo lo que escuchamos es una opinión, no un hecho. Todo lo que vemos es una perspectiva, no la verdad.", author: "Marco Aurelio" },
    { text: "La clave para la felicidad está en el ahora.", author: "Eckhart Tolle" },
    { text: "Mientras vivimos, aprendemos a vivir.", author: "Séneca" },
    { text: "No podemos elegir nuestras circunstancias externas, pero siempre podemos elegir cómo responder a ellas.", author: "Epicteto" },
    { text: "El silencio es una fuente de gran fuerza.", author: "Lao-Tsé" },
    { text: "Sé tolerante con los demás y estricto contigo mismo.", author: "Marco Aurelio" },
    { text: "La única forma de hacer un gran trabajo es amar lo que haces.", author: "Steve Jobs" },
    { text: "La gratitud convierte lo que tenemos en suficiente.", author: "Melody Beattie" },
    { text: "Somos lo que hacemos repetidamente. La excelencia, entonces, no es un acto, sino un hábito.", author: "Aristóteles" },
    { text: "El hombre que mueve una montaña comienza llevando pequeñas piedras.", author: "Confucio" },
    { text: "No sufrimos por los acontecimientos en nuestras vidas, sino por nuestros juicios sobre ellos.", author: "Epicteto" },
    { text: "La paz viene de adentro, no la busques afuera.", author: "Buda" },
    { text: "Un hombre sin propósito es como un barco sin timón.", author: "Thomas Carlyle" },
    { text: "La vida se encoge o se expande en proporción a la valentía de uno.", author: "Anaïs Nin" },
    { text: "Lo que se interpone en el camino se convierte en el camino.", author: "Marco Aurelio" },
    { text: "La sabiduría comienza con el asombro.", author: "Sócrates" },
    { text: "Preocúpate más por tu carácter que por tu reputación.", author: "John Wooden" },
    { text: "La vida no vivida es una enfermedad de la que se puede morir.", author: "Carl Jung" },
    { text: "La única sabiduría verdadera es saber que no sabes nada.", author: "Sócrates" },
    { text: "No es pobre el que tiene poco, sino el que mucho desea.", author: "Séneca" },
    { text: "El que domina a otros es fuerte; el que se domina a sí mismo es poderoso.", author: "Lao-Tsé" },
    { text: "Elige no ser dañado y no te sentirás dañado. No te sientas dañado y no lo habrás sido.", author: "Marco Aurelio" },
    { text: "La felicidad no es algo ya hecho. Viene de tus propias acciones.", author: "Dalai Lama" },
    { text: "Las dificultades preparan a personas comunes para destinos extraordinarios.", author: "C.S. Lewis" },
    { text: "Si quieres felicidad para toda la vida, ayuda a alguien.", author: "Proverbio Chino" },
    { text: "Elige un trabajo que ames, y no tendrás que trabajar ni un día de tu vida.", author: "Confucio" },
    { text: "Mantén tu rostro siempre hacia la luz del sol y las sombras caerán detrás de ti.", author: "Walt Whitman" },
    { text: "Un día sin reír es un día perdido.", author: "Charlie Chaplin" },
    { text: "La vida es un 10% lo que te sucede y un 90% cómo reaccionas a ello.", author: "Charles R. Swindoll" },
    { text: "La verdadera libertad es vivir el momento presente.", author: "Eckhart Tolle" },
    { text: "No se nos da una vida buena o mala. Se nos da una vida. Depende de nosotros hacerla buena o mala.", author: "Marco Aurelio" },
    { text: "El primer principio es que no debes engañarte a ti mismo, y tú eres la persona más fácil de engañar.", author: "Richard Feynman" },
    { text: "La paciencia es amarga, pero su fruto es dulce.", author: "Aristóteles" },
    { text: "Si no te gusta algo, cámbialo. Si no puedes cambiarlo, cambia tu actitud.", author: "Maya Angelou" },
    { text: "La mente lo es todo. En lo que piensas, te conviertes.", author: "Buda" },
    { text: "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", author: "Robert Collier" },
    { text: "No temas ir despacio, teme quedarte quieto.", author: "Proverbio Chino" },
    { text: "Todo lo que siempre has querido está al otro lado del miedo.", author: "George Addair" },
    { text: "La vida es una aventura atrevida o no es nada.", author: "Helen Keller" },
    { text: "Cree que puedes y ya estás a medio camino.", author: "Theodore Roosevelt" },
    { text: "Caerse siete veces, levantarse ocho.", author: "Proverbio Japonés" },
    { text: "Para evitar la crítica: no hagas nada, no digas nada, no seas nada.", author: "Aristóteles" },
    { text: "No cuentes los días, haz que los días cuenten.", author: "Muhammad Ali" },
    { text: "El mejor momento para plantar un árbol fue hace 20 años. El segundo mejor momento es ahora.", author: "Proverbio Chino" },
    { text: "Lo que la mente del hombre puede concebir y creer, puede lograrlo.", author: "Napoleon Hill" },
    { text: "La simplicidad es la gloria de la expresión.", author: "Walt Whitman" },
    { text: "No recibimos una vida corta, sino que nosotros la acortamos.", author: "Séneca" },
    { text: "La energía de la mente es la esencia de la vida.", author: "Aristóteles" },
    { text: "Entre el estímulo y la respuesta hay un espacio. En ese espacio reside nuestro poder para elegir nuestra respuesta.", author: "Viktor Frankl" },
    { text: "No es lo que te ocurre, sino cómo reaccionas lo que importa.", author: "Epicteto" },
    { text: "Alégrate porque todo lugar es aquí y todo momento es ahora.", author: "Buda" },
    { text: "El alma se tiñe del color de sus pensamientos.", author: "Marco Aurelio" },
    { text: "La vida no se mide por el número de respiraciones que tomamos, sino por los momentos que nos quitan el aliento.", author: "Maya Angelou" },
    { text: "Sé el cambio que quieres ver en el mundo.", author: "Mahatma Gandhi" },
    { text: "Un hombre que es dueño de sí mismo es más grande que el que es dueño del mundo.", author: "Marco Aurelio" },
    { text: "La felicidad no es la ausencia de problemas, es la habilidad de tratar con ellos.", author: "Steve Maraboli" },
    { text: "Cuando dejas de buscar, encuentras.", author: "Lao-Tsé" },
    { text: "El que vive en armonía consigo mismo, vive en armonía con el universo.", author: "Marco Aurelio" },
    { text: "La vida es un eco. Lo que envías, regresa. Lo que siembras, cosechas.", author: "Zig Ziglar" },
    { text: "No puedes tener una vida positiva y una mente negativa.", author: "Joyce Meyer" },
    { text: "La mejor manera de predecir el futuro es crearlo.", author: "Peter Drucker" },
    { text: "La preocupación no elimina las penas del mañana, solo vacía las fuerzas de hoy.", author: "Corrie ten Boom" },
    { text: "La mente es como un paracaídas. No funciona si no se abre.", author: "Frank Zappa" },
    { text: "La disciplina es el puente entre las metas y los logros.", author: "Jim Rohn" },
    { text: "Sé tú mismo; todos los demás ya están ocupados.", author: "Oscar Wilde" },
    { text: "Si la oportunidad no llama, construye una puerta.", author: "Milton Berle" },
    { text: "No juzgues cada día por la cosecha que recoges, sino por las semillas que plantas.", author: "Robert Louis Stevenson" },
    { text: "El optimismo es la fe que conduce al logro.", author: "Helen Keller" },
    { text: "Haz lo que puedas, con lo que tengas, donde estés.", author: "Theodore Roosevelt" },
    { text: "Todo el mundo piensa en cambiar el mundo, pero nadie piensa en cambiarse a sí mismo.", author: "León Tolstói" },
    { text: "No hay camino a la felicidad, la felicidad es el camino.", author: "Buda" },
    { text: "La acción es la clave fundamental para todo éxito.", author: "Pablo Picasso" },
    { text: "El conocimiento habla, pero la sabiduría escucha.", author: "Jimi Hendrix" },
    { text: "Cuanto más medites en los buenos pensamientos, mejor será tu mundo y el mundo en general.", author: "Confucio" },
    { text: "La persona que dice que no se puede hacer no debería interrumpir a la persona que lo está haciendo.", author: "Proverbio chino" },
    { text: "Un pequeño cambio positivo puede cambiar tu día entero o tu vida entera.", author: "Anónimo" },
    { text: "La vida es como una cámara: enfócate en lo importante, captura los buenos momentos, saca de lo negativo y, si las cosas no salen, toma otra foto.", author: "Anónimo" },
    { text: "El fracaso es éxito si aprendemos de él.", author: "Malcolm Forbes" },
    { text: "No puedes volver atrás y cambiar el principio, pero puedes empezar donde estás y cambiar el final.", author: "C.S. Lewis" },
    { text: "La motivación es lo que te pone en marcha. El hábito es lo que hace que sigas.", author: "Jim Ryun" },
    { text: "Casi todo volverá a funcionar si lo desconectas por unos minutos... incluyéndote a ti.", author: "Anne Lamott" },
    { text: "Respira hondo. Es solo un mal día, no una mala vida.", author: "Anónimo" },
    { text: "La verdadera meditación es sobre ser plenamente presente con todo lo que es.", author: "Jon Kabat-Zinn" },
    { text: "Tu calma es tu superpoder.", author: "Anónimo" },
    { text: "La mente es como el agua. Cuando está turbulenta, es difícil ver. Cuando está en calma, todo se vuelve claro.", author: "Prasad Mahes" },
    { text: "Habla contigo mismo como lo harías con alguien a quien amas.", author: "Brené Brown" },
    { text: "Nada puede atenuar la luz que brilla desde adentro.", author: "Maya Angelou" },
    { text: "En medio del movimiento y el caos, mantén la quietud dentro de ti.", author: "Deepak Chopra" },
    { text: "El acto de bondad más pequeño vale más que la intención más grandiosa.", author: "Oscar Wilde" },
    { text: "La gratitud da sentido a nuestro pasado, trae paz para hoy y crea una visión para el mañana.", author: "Melody Beattie" },
    { text: "La felicidad no es tener lo que quieres, sino querer lo que tienes.", author: "Rabbi Hyman Schachtel" },
    { text: "Sé agradecido por lo que tienes; terminarás teniendo más.", author: "Oprah Winfrey" },
    { text: "El sol es un recordatorio diario de que nosotros también podemos levantarnos de la oscuridad.", author: "Anónimo" },
    { text: "Un corazón agradecido es un imán para los milagros.", author: "Anónimo" },
    { text: "Recuerda que no obtener lo que quieres a veces es un maravilloso golpe de suerte.", author: "Dalai Lama" },
    { text: "La amabilidad es el lenguaje que los sordos pueden oír y los ciegos pueden ver.", author: "Mark Twain" },
    { text: "No te preocupes por los fracasos, preocúpate por las oportunidades que pierdes cuando ni siquiera lo intentas.", author: "Jack Canfield" },
    { text: "El presente es el único momento que importa.", author: "Thich Nhat Hanh" },
    { text: "Tu tarea no es buscar el amor, sino simplemente buscar y encontrar todas las barreras dentro de ti que has construido contra él.", author: "Rumi" },
    { text: "Comienza donde estás. Usa lo que tienes. Haz lo que puedas.", author: "Arthur Ashe" },
    { text: "El arte de la sabiduría es el arte de saber qué pasar por alto.", author: "William James" },
    { text: "La vida es un misterio a vivir, no un problema a resolver.", author: "Osho" },
    { text: "Cada mañana nacemos de nuevo. Lo que hacemos hoy es lo que más importa.", author: "Buda" },
    { text: "No dejes que el comportamiento de otros destruya tu paz interior.", author: "Dalai Lama" },
    { text: "La mayor gloria no es no caer nunca, sino levantarse cada vez que caes.", author: "Confucio" },
    { text: "La felicidad es interior, no exterior; por lo tanto, no depende de lo que tenemos, sino de lo que somos.", author: "Henry Van Dyke" },
    { text: "Sé una luz para ti mismo.", author: "Buda" },
    { text: "El secreto de la salud, tanto para la mente como para el cuerpo, no es lamentarse por el pasado, ni preocuparse por el futuro, sino vivir el momento presente sabia y seriamente.", author: "Buda" },
    { text: "La paciencia y la perseverancia tienen un efecto mágico ante el cual las dificultades desaparecen y los obstáculos se desvanecen.", author: "John Quincy Adams" },
    { text: "No es la carga lo que te rompe, sino la forma en que la llevas.", author: "Lou Holtz" },
    { text: "Transforma tus heridas en sabiduría.", author: "Oprah Winfrey" },
    { text: "La vida es como andar en bicicleta. Para mantener el equilibrio, debes seguir moviéndote.", author: "Albert Einstein" },
    { text: "El éxito no es definitivo, el fracaso no es fatal: es el coraje para continuar lo que cuenta.", author: "Winston Churchill" },
    { text: "Lo que obtienes al alcanzar tus metas no es tan importante como en lo que te conviertes al alcanzar tus metas.", author: "Zig Ziglar" },
    { text: "El futuro pertenece a quienes creen en la belleza de sus sueños.", author: "Eleanor Roosevelt" },
    { text: "No puedes controlar el viento, pero puedes ajustar las velas.", author: "Proverbio" },
    { text: "Si buscas la perfección, nunca estarás contento.", author: "León Tolstói" },
    { text: "La verdadera sabiduría está en reconocer la propia ignorancia.", author: "Sócrates" },
    { text: "La mejor manera de empezar es dejar de hablar y empezar a hacer.", author: "Walt Disney" },
    { text: "Somos lo que pensamos. Todo lo que somos surge con nuestros pensamientos. Con nuestros pensamientos, hacemos el mundo.", author: "Buda" },
    { text: "La mejor forma de animarte es intentar animar a otra persona.", author: "Mark Twain" },
    { text: "Una mente negativa nunca te dará una vida positiva.", author: "Anónimo" },
    { text: "La felicidad es una mariposa que, cuando la persigues, siempre está fuera de tu alcance, pero que, si te sientas en silencio, puede posarse sobre ti.", author: "Nathaniel Hawthorne" },
    { text: "Sé amable, porque toda persona que conoces está librando una gran batalla.", author: "Platón" },
    { text: "Elige ser optimista, se siente mejor.", author: "Dalai Lama" },
    { text: "Cuando una puerta de la felicidad se cierra, otra se abre.", author: "Helen Keller" },
    { text: "Lo que no te mata te hace más fuerte.", author: "Friedrich Nietzsche" },
    { text: "No hay nada noble en ser superior a tu prójimo; la verdadera nobleza es ser superior a tu yo anterior.", author: "Ernest Hemingway" },
    { text: "La vida es el arte de dibujar sin goma de borrar.", author: "John W. Gardner" },
    { text: "No esperes. El tiempo nunca será el adecuado.", author: "Napoleon Hill" },
    { text: "La preocupación es un mal uso de la imaginación.", author: "Anónimo" },
    { text: "No hay atajos para ningún lugar al que valga la pena ir.", author: "Beverly Sills" },
    { text: "La felicidad no es un destino, es una forma de vida.", author: "Anónimo" },
    { text: "La manera de desarrollar la autoconfianza es hacer lo que temes.", author: "William Jennings Bryan" },
    { text: "El carácter no se puede desarrollar en la facilidad y la quietud. Solo a través de la experiencia se puede fortalecer el alma.", author: "Helen Keller" },
    { text: "Nuestra mayor debilidad radica en rendirnos. La forma más segura de tener éxito es siempre intentarlo una vez más.", author: "Thomas A. Edison" },
    { text: "La vida no se trata de encontrarte a ti mismo. La vida se trata de crearte a ti mismo.", author: "George Bernard Shaw" },
    { text: "El único verdadero viaje de descubrimiento no consiste en buscar nuevos paisajes, sino en tener nuevos ojos.", author: "Marcel Proust" },
    { text: "No podemos resolver nuestros problemas con el mismo pensamiento que usamos cuando los creamos.", author: "Albert Einstein" },
    { text: "La libertad no es la ausencia de compromisos, sino la capacidad de elegir.", author: "Paulo Coelho" },
    { text: "La vida es una obra de teatro que no permite ensayos. Por eso, canta, ríe, baila, llora y vive intensamente.", author: "Charlie Chaplin" },
    { text: "La mente que se abre a una nueva idea nunca vuelve a su tamaño original.", author: "Albert Einstein" },
    { text: "La calidad de tu vida es la calidad de tus relaciones.", author: "Tony Robbins" },
    { text: "El dolor es inevitable. El sufrimiento es opcional.", author: "Haruki Murakami" },
    { text: "La simplicidad, la paciencia, la compasión. Estos tres son tus mayores tesoros.", author: "Lao-Tsé" },
    { text: "No se puede encontrar la paz evitando la vida.", author: "Virginia Woolf" },
    { text: "El secreto para salir adelante es empezar.", author: "Mark Twain" },
    { text: "Si quieres levantar a los demás, primero levántate a ti mismo.", author: "Booker T. Washington" },
    { text: "Un corazón en paz da vida al cuerpo.", author: "Proverbios 14:30" },
    { text: "La meditación trae sabiduría; la falta de meditación deja ignorancia.", author: "Buda" },
    { text: "Dentro de ti hay una quietud y un santuario al que puedes retirarte en cualquier momento y ser tú mismo.", author: "Hermann Hesse" },
    { text: "Tu visión se aclarará solo cuando puedas mirar dentro de tu propio corazón.", author: "Carl Jung" },
    { text: "Aprende a estar en calma y realmente escucharás.", author: "Proverbio" },
    { text: "La calma es la cuna del poder.", author: "Josiah Gilbert Holland" },
    { text: "Respira. Suelta. Y recuerda que este mismo momento es el único que sabes que tienes con seguridad.", author: "Oprah Winfrey" },
    { text: "La mente es un instrumento flexible. Aprende a usarlo.", author: "Epicteto" },
    { text: "La serenidad es la tranquilidad de un alma ordenada.", author: "Séneca" },
    { text: "La verdadera felicidad es disfrutar el presente, sin una dependencia ansiosa del futuro.", author: "Séneca" },
    { text: "Un mar en calma no hace a un marinero hábil.", author: "Proverbio Africano" },
    { text: "La quietud no está vacía, está llena de respuestas.", author: "Anónimo" },
    { text: "El alma siempre sabe qué hacer para curarse a sí misma. El desafío es silenciar la mente.", author: "Caroline Myss" },
    { text: "La vida comienza al final de tu zona de confort.", author: "Neale Donald Walsch" },
    { text: "El que tiene un porqué para vivir puede soportar casi cualquier cómo.", author: "Friedrich Nietzsche" },
    { text: "El éxito consiste en ir de fracaso en fracaso sin pérdida de entusiasmo.", author: "Winston Churchill" },
    { text: "La mayor aventura que puedes emprender es vivir la vida de tus sueños.", author: "Oprah Winfrey" },
    { text: "El propósito de la vida no es ser feliz. Es ser útil, ser honorable, ser compasivo.", author: "Ralph Waldo Emerson" },
    { text: "Nunca eres demasiado viejo para fijar otra meta o para soñar un nuevo sueño.", author: "C.S. Lewis" },
    { text: "Lo que haces hoy puede mejorar todos tus mañanas.", author: "Ralph Marston" },
    { text: "Si escuchas una voz dentro de ti que dice 'no puedes pintar', entonces pinta, y esa voz será silenciada.", author: "Vincent Van Gogh" },
    { text: "La felicidad es cuando lo que piensas, lo que dices y lo que haces están en armonía.", author: "Mahatma Gandhi" },
    { text: "La mejor preparación para el mañana es hacer tu mejor trabajo hoy.", author: "H. Jackson Brown, Jr." },
    { text: "El único límite para nuestra realización del mañana serán nuestras dudas de hoy.", author: "Franklin D. Roosevelt" },
    { text: "Sé feliz por este momento. Este momento es tu vida.", author: "Omar Khayyam" },
    { text: "El cambio es la ley de la vida. Y aquellos que solo miran al pasado o al presente, seguramente se perderán el futuro.", author: "John F. Kennedy" },
    { text: "No tienes que ser grande para empezar, pero tienes que empezar para ser grande.", author: "Zig Ziglar" },
    { text: "La vida es una sucesión de lecciones que deben ser vividas para ser entendidas.", author: "Ralph Waldo Emerson" },
    { text: "La vida es como el jazz... es mejor cuando improvisas.", author: "George Gershwin" },
    { text: "La vida es como una moneda. Puedes gastarla de la manera que desees, pero solo la gastas una vez.", author: "Lillian Dickson" },
    { text: "Haz de cada día tu obra maestra.", author: "John Wooden" },
    { text: "La clave de la inmortalidad es primero vivir una vida que valga la pena recordar.", author: "Bruce Lee" },
    { text: "La vida es una flor de la cual el amor es la miel.", author: "Victor Hugo" },
    { text: "No recuerdo los días, recuerdo los momentos.", author: "Cesare Pavese" },
    { text: "La vida no se trata de esperar a que pase la tormenta, sino de aprender a bailar bajo la lluvia.", author: "Vivian Greene" },
    { text: "La vida es un viaje, no un destino.", author: "Ralph Waldo Emerson" },
    { text: "Vivir es lo más raro del mundo. La mayoría de la gente existe, eso es todo.", author: "Oscar Wilde" },
    { text: "La vida es una oportunidad, benefíciate de ella. La vida es belleza, admírala. La vida es un sueño, alcánzalo.", author: "Madre Teresa" },
    { text: "El propósito de nuestras vidas es ser felices.", author: "Dalai Lama" },
    { text: "La vida es corta, y está aquí para ser vivida.", author: "Kate Winslet" },
    { text: "La vida es un juego, juégalo; es un desafío, enfréntalo; es una oportunidad, aprovéchala.", author: "Anónimo" },
    { text: "La gratitud es la memoria del corazón.", author: "Jean Baptiste Massieu" },
    { text: "La gratitud no es solo la más grande de las virtudes, sino la madre de todas las demás.", author: "Cicerón" },
    { text: "La gratitud puede transformar los días comunes en días de acción de gracias.", author: "William Arthur Ward" },
    { text: "La gratitud es el vino para el alma. Adelante. Emborráchate.", author: "Rumi" },
    { text: "Cuando te levantes por la mañana, piensa en el precioso privilegio que es estar vivo.", author: "Marco Aurelio" },
    { text: "La gratitud desbloquea la plenitud de la vida. Convierte lo que tenemos en suficiente, y más.", author: "Melody Beattie" },
    { text: "La gratitud es la flor más hermosa que brota del alma.", author: "Henry Ward Beecher" },
    { text: "Siente gratitud por todo. Las buenas, las malas, las feas. Todas son lecciones.", author: "Anónimo" },
    { text: "La gratitud es la forma más exquisita de cortesía.", author: "Jacques Maritain" },
    { text: "La gratitud es el comienzo de la grandeza. Es el comienzo de la maravilla.", author: "Anónimo" },
    { text: "La gratitud es la mejor medicina. Cura tanto al que la da como al que la recibe.", author: "Anónimo" },
    { text: "La gratitud es un músculo. Cuanto más lo usas, más fuerte se vuelve.", author: "Anónimo" },
    { text: "La gratitud es el antídoto para el veneno de la envidia.", author: "Anónimo" },
    { text: "La gratitud es la clave que abre la puerta a la abundancia.", author: "Anónimo" },
    { text: "La gratitud es la semilla de la que brota la felicidad.", author: "Anónimo" },
    { text: "La gratitud es la fragancia de un alma noble.", author: "Anónimo" },
    { text: "La gratitud es la luz que ilumina el camino de la vida.", author: "Anónimo" },
    { text: "La gratitud que compartes es la gratitud que recibes.", author: "Anónimo" },
    { text: "La vida es cambio. El crecimiento es opcional. Elige sabiamente.", author: "Karen Kaiser Clark" },
    { text: "No puedes detener las olas, pero puedes aprender a surfear.", author: "Jon Kabat-Zinn" },
    { text: "A veces, soltar es el acto más poderoso.", author: "Anónimo" },
    { text: "El cambio es el resultado final de todo verdadero aprendizaje.", author: "Leo Buscaglia" },
    { text: "Aquellos que no pueden cambiar de opinión no pueden cambiar nada.", author: "George Bernard Shaw" },
    { text: "Si no te gusta dónde estás, muévete. No eres un árbol.", author: "Jim Rohn" },
    { text: "Cada nuevo día es otra oportunidad para cambiar tu vida.", author: "Anónimo" },
    { text: "El progreso es imposible sin cambio.", author: "George Bernard Shaw" },
    { text: "El cambio puede ser aterrador, pero permitir que el miedo te impida crecer es más aterrador.", author: "Mandy Hale" },
    { text: "El cambio es inevitable. El crecimiento es intencional.", author: "Glenda Cloud" },
    { text: "Tu vida no mejora por casualidad, mejora por cambio.", author: "Jim Rohn" },
    { text: "El cambio es difícil al principio, desordenado en el medio y hermoso al final.", author: "Robin Sharma" },
    { text: "El cambio es la única constante en la vida.", author: "Heráclito" },
    { text: "El cambio no siempre es fácil, pero siempre es posible.", author: "Barack Obama" },
    { text: "El cambio comienza al final de tu zona de confort.", author: "Anónimo" },
    { text: "La oscuridad no puede expulsar a la oscuridad; solo la luz puede hacer eso. El odio no puede expulsar al odio; solo el amor puede hacer eso.", author: "Martin Luther King, Jr." },
    { text: "La felicidad se puede encontrar, incluso en los tiempos más oscuros, si uno solo recuerda encender la luz.", author: "Albus Dumbledore" },
    { text: "La esperanza es poder ver que hay luz a pesar de toda la oscuridad.", author: "Desmond Tutu" },
    { text: "Hay una grieta en todo, así es como entra la luz.", author: "Leonard Cohen" },
    { text: "La luz que buscas está dentro de ti.", author: "Anónimo" },
    { text: "En la fe hay suficiente luz para aquellos que quieren creer y suficientes sombras para cegar a los que no.", author: "Blaise Pascal" },
    { text: "La luz del conocimiento disipa la oscuridad de la ignorancia.", author: "Anónimo" },
    { text: "La luz del amor puede derretir el corazón más frío.", author: "Anónimo" },
    { text: "La luz de la risa puede alegrar el día más sombrío.", author: "Anónimo" },
    { text: "La luz de la gratitud puede transformar la escasez en abundancia.", author: "Anónimo" },
    { text: "La luz de la fe puede mover montañas.", author: "Anónimo" },
    { text: "La luz de la paciencia puede calmar la mente más inquieta.", author: "Anónimo" },
    { text: "La luz de la compasión puede curar las heridas más profundas.", author: "Anónimo" },
    { text: "La luz de la sabiduría puede guiarte a través del laberinto de la vida.", author: "Anónimo" },
    { text: "La luz que compartes es la luz que recibes.", author: "Anónimo" },
    { text: "En la profundidad del invierno, finalmente aprendí que dentro de mí yace un verano invencible.", author: "Albert Camus" },
    { text: "El color de la quietud es la imaginación.", author: "Anónimo" },
    { text: "La quietud no es una estación, es una celebración.", author: "Anamika Mishra" },
    { text: "El silencio es un tiempo de espera, un tiempo de fe, un tiempo para volverse hacia adentro.", author: "Anónimo" },
    { text: "La quietud es una promesa de claridad.", author: "Anónimo" },
    { text: "La quietud es una temporada de recuperación y preparación.", author: "Paul Theroux" },
    { text: "La quietud es el comienzo de algo nuevo.", author: "Anónimo" },
    { text: "La quietud es una excusa para abrazos más largos al alma.", author: "Anónimo" },
    { text: "La quietud es una sinfonía de silencio.", author: "Anónimo" },
    { text: "La quietud es una invitación a la introspección.", author: "Anónimo" },
    { text: "La quietud es una lección de paciencia.", author: "Anónimo" },
    { text: "La quietud es una canción de cuna para el alma.", author: "Anónimo" },
    { text: "La quietud es un poema escrito en el cielo del ser.", author: "Anónimo" },
    { text: "La quietud es una historia contada por el viento interior.", author: "Anónimo" },
    { text: "La quietud es una pintura de la naturaleza del ser.", author: "Anónimo" },
    { text: "La quietud es una escultura de hielo mental que se derrite en paz.", author: "Anónimo" },
    { text: "La quietud es una melodía de tranquilidad.", author: "Anónimo" },
    { text: "La quietud es un sueño de renacimiento interior.", author: "Anónimo" },
    { text: "La quietud es una promesa de renovación.", author: "Anónimo" },
    { text: "La quietud es una celebración del ser.", author: "Anónimo" },
    { text: "La quietud es un regalo de la naturaleza.", author: "Anónimo" },
    { text: "La quietud es un tiempo para reflexionar y soñar.", author: "Anónimo" },
    { text: "La quietud es un capítulo en la historia de la vida.", author: "Anónimo" },
    { text: "La quietud es un lienzo en blanco esperando ser pintado con paz.", author: "Anónimo" },
    { text: "La quietud es una oportunidad para encontrar calor en el propio corazón.", author: "Anónimo" },
    { text: "La quietud es una razón para ser agradecido por el sol interior.", author: "Anónimo" },
    { text: "La amabilidad es hacer algo extra por alguien.", author: "Charles M. Schulz" },
    { text: "La compasión es un puente. Necesitamos puentes a medida que el río del tiempo fluye.", author: "Gladys Taber" },
    { text: "La generosidad es una necesidad. Tiene que haber al menos un día del año para recordarnos que estamos aquí para algo más que nosotros mismos.", author: "Eric Sevareid" },
    { text: "El amor es un pedazo de hogar que uno lleva en el corazón.", author: "Anónimo" },
    { text: "La bondad es el espíritu de dar sin pensar en recibir.", author: "Anónimo" },
    { text: "El amor es la acción. Cada vez que amamos, cada vez que damos, es una celebración.", author: "Dale Evans" },
    { text: "Hoy es un tiempo para la nostalgia, pero también es un tiempo para hacer nuevos recuerdos.", author: "Anónimo" },
    { text: "Hoy es un tiempo para creer en la magia.", author: "Anónimo" },
    { text: "Hoy es un tiempo para perdonar y ser perdonado.", author: "Anónimo" },
    { text: "Hoy es un tiempo para compartir y cuidar.", author: "Anónimo" },
    { text: "Hoy es un tiempo para la familia y los amigos.", author: "Anónimo" },
    { text: "Hoy es un tiempo para la esperanza y la paz.", author: "Anónimo" },
    { text: "Hoy es un tiempo para la gratitud y la alegría.", author: "Anónimo" },
    { text: "Hoy es un tiempo para la generosidad y la bondad.", author: "Anónimo" },
    { text: "Hoy es un tiempo para la fe y el amor.", author: "Anónimo" },
    { text: "Hoy es un tiempo para la reflexión y la renovación.", author: "Anónimo" },
    { text: "Hoy es un tiempo para celebrar la vida.", author: "Anónimo" },
    { text: "Hoy es un tiempo para soñar y desear.", author: "Anónimo" },
    { text: "Hoy es un tiempo para recordar a nuestros seres queridos.", author: "Anónimo" },
    { text: "Hoy es un tiempo para crear tradiciones.", author: "Anónimo" },
    { text: "Hoy es un tiempo para disfrutar de las pequeñas cosas.", author: "Anónimo" },
    { text: "Hoy es un tiempo para ser un niño otra vez.", author: "Anónimo" },
    { text: "Hoy es un tiempo para ser feliz.", author: "Anónimo" },
    { text: "Hoy es un tiempo para sonreír.", author: "Anónimo" },
    { text: "Hoy es un tiempo para amar.", author: "Anónimo" },
    { text: "Hoy es un tiempo para vivir.", author: "Anónimo" },
    { text: "El fin de un ciclo no es ni un fin ni un comienzo, sino una continuación, con toda la sabiduría que la experiencia puede inculcar en nosotros.", author: "Hal Borland" }
];