// Archivo de frases para el Temporizador de Meditación

const finalQuotes = [
    { text: "Lo primero que se necesita para vivir el presente es foco: atención plena en aquello que se esté haciendo.", author: "Francesc Miralles" },
    { text: "La felicidad verdadera no está en el tener, sino en el ser.", author: "Marian Rojas Estapé" },
    { text: "La felicidad no es lo que nos pasa, sino cómo interpretamos lo que nos pasa.", author: "Marian Rojas Estapé" },
    { text: "Vivir en constante alerta, angustia o tristeza impide encontrar la paz para ser felices.", author: "Marian Rojas Estapé" },
    { text: "Si abrimos una disputa entre pasado y presente, encontraremos que hemos perdido el futuro.", author: "Winston Churchill" },
    { text: "Si pasas por el infierno, sigue adelante.", author: "Winston Churchill" },
    { text: "Soy un optimista. No tiene mucho sentido ser otra cosa.", author: "Winston Churchill" },
    { text: "Entre el estímulo y la respuesta hay un espacio; en ese espacio tenemos el poder de elegir nuestra respuesta.", author: "Viktor Frankl" },
    { text: "Todo ser humano tiene la libertad de cambiar en cualquier instante.", author: "Viktor Frankl" },
    { text: "Tener el corazón abierto, prestar atención sin prejuicios, a lo que pasa y no a lo que yo creía que debía pasar.", author: "Andrés Martín-Asuero" },
    { text: "La vida es una serie de momentos presentes.", author: "Eckhart Tolle" },
    { text: "La clave para la felicidad está en el ahora.", author: "Eckhart Tolle" },
    { text: "La verdadera libertad es vivir el momento presente.", author: "Eckhart Tolle" },
    { text: "Alégrate porque todo lugar es aquí y todo momento es ahora.", author: "Buda" },
    { text: "No es más rico quien más tiene, sino quien menos necesita.", author: "Buda" },
    { text: "La paz viene de adentro, no la busques afuera.", author: "Buda" },
    { text: "No es pobre el que tiene poco, sino el que mucho desea.", author: "Séneca" },
    { text: "No recibimos una vida corta, sino que nosotros la acortamos.", author: "Séneca" },
    { text: "La mejor riqueza es contentarse viviendo con poco.", author: "Platón" },
    { text: "La felicidad depende de nosotros mismos.", author: "Aristóteles" },
    { text: "La energía de la mente es la esencia de la vida.", author: "Aristóteles" },
    { text: "El ser humano solamente será feliz si utiliza todas sus capacidades y posibilidades.", author: "Jostein Gaarder" },
    { text: "La felicidad no es el premio a la virtud, sino la virtud misma.", author: "Baruch Spinoza" },
    { text: "Un hombre libre en nada piensa menos que en la muerte, y su sabiduría no es una meditación de la muerte, sino de la vida.", author: "Baruch Spinoza" },
    { text: "La felicidad humana es una disposición de la mente, no una condición de las circunstancias.", author: "John Locke" },
    { text: "La ocupación última del hombre es ser feliz.", author: "John Locke" },
    { text: "La vida feliz y dichosa es el objeto único de toda la filosofía.", author: "Cicerón" },
    { text: "No vayas fuera de ti, entra dentro de ti, que en tu interior encontrarás la verdad de quién eres.", author: "San Agustín de Hipona" },
    { text: "Luchemos por alcanzar la serenidad de aceptar las cosas inevitables, el valor de cambiar las cosas que podamos y la sabiduría para distinguir unas de otras.", author: "Reinhold Niebuhr" },
    { text: "Señor, hazme un instrumento de tu paz.", author: "Oración atribuida a San Francisco de Asís" },
    { text: "Nuestro principal deseo es alguien que nos inspire a ser lo que sabemos que podríamos ser.", author: "Ralph Waldo Emerson" },
    { text: "La felicidad es un perfume que no se puede derramar en los demás sin conseguir antes uno para sí mismo.", author: "Ralph Waldo Emerson" },
    { text: "Mantén tu rostro siempre hacia la luz del sol y las sombras caerán detrás de ti.", author: "Walt Whitman" },
    { text: "La simplicidad es la gloria de la expresión.", author: "Walt Whitman" },
    { text: "No cuentes los días, haz que los días cuenten.", author: "Muhammad Ali" },
    { text: "Lo que no se hace consciente se manifiesta en nuestra vida como destino.", author: "Carl Gustav Jung" },
    { text: "La vida no vivida es una enfermedad de la que se puede morir.", author: "Carl Gustav Jung" },
    { text: "La gratitud convierte lo que tenemos en suficiente.", author: "Melody Beattie" },
    { text: "La única forma de hacer un gran trabajo es amar lo que haces.", author: "Steve Jobs" },
    { text: "Solo hay una manera de evitar las críticas: no hacer nada, no decir nada, ni ser nada.", author: "Aristóteles" },
    { text: "Vivir es lo más raro; la mayoría de la gente existe, eso es todo.", author: "Oscar Wilde" },
    { text: "Todo el mundo piensa en cambiar al mundo, pero nadie piensa en cambiarse a sí mismo.", author: "León Tolstói" },
    { text: "La calidad de tu vida es la calidad de tus pensamientos.", author: "Marco Aurelio" },
    { text: "Las dificultades preparan a personas comunes para destinos extraordinarios.", author: "C.S. Lewis" },
    { text: "El viaje de mil millas comienza con un solo paso.", author: "Lao-Tsé" }
];